<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Domain/CryptoPaymentEngine.Gateway.Core.Platform.Audit.Domain.csproj" />
    <ProjectReference Include="../../../../SharedKernel/CryptoPaymentEngine.SharedKernel/CryptoPaymentEngine.SharedKernel.csproj" />
  </ItemGroup>

</Project>
