// <auto-generated />
using System;
using System.Numerics;
using CryptoPaymentEngine.Gateway.Core.AssetManagement.Energy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoPaymentEngine.Gateway.Core.AssetManagement.Energy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnergyDbContext))]
    partial class EnergyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("energy")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptoPaymentEngine.Gateway.Core.AssetManagement.Energy.Domain.EnergyOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<BigInteger>("AmountSun")
                        .HasColumnType("decimal(38,0)");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("Confirmations")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("OwnerAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<byte[]>("SignedTransaction")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("SigningRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StakingWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TargetAddress")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.HasIndex("StakingWalletId")
                        .IsUnique()
                        .HasDatabaseName("UX_EnergyOp_InFlight_Stake")
                        .HasFilter("[Kind] = 'Stake' AND [Status] IN ('Pending', 'Signing', 'Broadcast')");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_EnergyOp_Status");

                    b.HasIndex("Chain", "TargetAddress")
                        .IsUnique()
                        .HasDatabaseName("UX_EnergyOp_InFlight_Delegate")
                        .HasFilter("[Kind] = 'Delegate' AND [Status] IN ('Pending', 'Signing', 'Broadcast')");

                    b.ToTable("EnergyOperation", "energy");
                });

            modelBuilder.Entity("CryptoPaymentEngine.Gateway.Core.AssetManagement.Energy.Domain.EnergyPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EnableAutoRent")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableAutoStake")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<BigInteger>("MinimumEnergy")
                        .HasColumnType("decimal(38,0)");

                    b.Property<BigInteger>("RentalThreshold")
                        .HasColumnType("decimal(38,0)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<BigInteger>("StakeThreshold")
                        .HasColumnType("decimal(38,0)");

                    b.Property<BigInteger>("TargetEnergy")
                        .HasColumnType("decimal(38,0)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WalletType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("Chain", "WalletType")
                        .IsUnique();

                    b.ToTable("EnergyPolicy", "energy");
                });

            modelBuilder.Entity("CryptoPaymentEngine.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ProcessedOnUtc")
                        .HasFilter("[ProcessedOnUtc] IS NULL");

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.ToTable("OutboxMessage", "energy");
                });
#pragma warning restore 612, 618
        }
    }
}
